### PR TITLE
Imperva WAF sample events

### PR DESCRIPTION
**Pull request by mchavda-splunk**
Hi @rfaircloth-splunk , @mbonsack , We want to assign source types based on the event_class (the 5th field in the CEF header) field of the header. and **cat** field of event
For Example:

|Sourcetype|Description|
|:-:|:-:|
| imperva:waf:system:cef | Events with **cat=SystemEvent** value |
| imperva:waf:firewall:cef | Events with **Firewall** event_class |
| imperva:waf:security:cef| Events with  **Signature** OR **Protocol** OR **Worm** event_class |
|imperva:waf | All other Imperva \| SecureSphere events |

As the SC4S only allows device_vendor and device_product fields for source type and index mapping in the common_event_format_source.csv file, we want some way to map events based on event class and a way to match regex to the event message.

Also, we don't want to drop the header part from the events.

### CODE REVIEW

**Comment by mchavda-splunk** [comment]
```
Jul 16 18:19:52 3.3.3.3 CEF:0|Imperva Inc.|SecureSphere|10.5.0|Worm|Web Worm|High|act=Block dst=1.1.1.1 dpt=80 duser=n/a src=1.0.0.1 spt=65535 proto=TCP rt=Jul 16 2015 18:19:50 cat=Alert cs1=Web Worm Policy cs1Label=Policy cs2=Server3 cs2Label=ServerGroup cs3=ServiceName3 cs3Label=ServiceName cs4=ApplicationName3 cs4Label=ApplicationName cs5=Access to: /cgi-system/rtpd.cgi cs5Label=Description

7/29/2015 10:16 AM,Info,10.1.12.39,CEF:0|Imperva Inc.|SecureSphere|11.5.0|Login failed|Login failed for user asdasdasdasd (IP: 10.2.140.5) Reason: bad credentials|High|suser=System rt=Jul 14 2015 10:05:51 cat=SystemEvent
```
Other than above two events, All events are the latest (Jan 30 2020)

**Comment by rfaircloth-splunk** [comment]
the two samples above literally say 2015 meaning 5 years old and are not correctly formatted CEF. I know a couple of customers have reported success using Imperva with SC4S so I am concerned we should not code off of these

**Comment by mchavda-splunk** [comment]
@rfaircloth-splunk I have removed the invalid CEF event from [your branch](https://github.com/splunk/splunk-connect-for-syslog/compare/mchavda-splunk/imperva-waf-test-cases-424). We still need to send the complete event to the Splunk without removing the header part. Could you please help with it.

**Comment by mchavda-splunk** [comment]
Link to your branch: https://github.com/splunk/splunk-connect-for-syslog/compare/mchavda-splunk/imperva-waf-test-cases-424

**Pull request closed without merging**
