### PR TITLE
juniper_junos_unstructured: add message filter to junos

### PR DESCRIPTION
**Pull request by zyphermonkey**
New message discovered from juniper os device.

### CODE REVIEW

**Review by ikheifets-splunk — APPROVED** [review]

**Comment by ikheifets-splunk** [comment]
@zyphermonkey please sign CLA and we will merge it. I already approved that

**Comment by zyphermonkey** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by zyphermonkey** [comment]
recheck

**Pull request merged**
