### PR TITLE
feat(t_templates): use syslog-ng default substitution instead of $(if)

### PR DESCRIPTION
**Pull request by bazsi**
This is a tiny improvement I use mainly to see how the contribution process works and also to get to know Github actions which don't run on my fork. I don't insist on merging this, I am just trying to get more familiar with sc4s.

### CODE REVIEW

**Comment by rfaircloth-splunk** [comment]
Oh nice syntax I learned something which I usually do when I look at your work. I approved the CI run but I need you to accept the cla/coc agrements to merge

**Comment by bazsi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bazsi** [comment]
I could only find the CoC in the GitHub actions config, but there's no link posted by the bot and the CoC is not part of the project's GitHub settings.

**Comment by bazsi** [comment]
https://github.com/splunk/cla-agreement/blob/main/CODE_OF_CONDUCT.md

I have read the Code of Conduct and I hereby accept the Terms

**Comment by bazsi** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by bazsi** [comment]
It seems I have no permission to push the docker image generated from this PR into the github docker registry. It is understandable, but it seems the CI is not able to run this way.

**Pull request merged**
