### PR TITLE
syslog-ng v4.2 upgrade

### PR DESCRIPTION
**Pull request by MrAnno**
This is an attempt to upgrade to syslog-ng v4.2 (upcoming version).

Test results (based on `ghcr.io/axoflow/syslog-ng:nightly`):
https://github.com/MrAnno/splunk-connect-for-syslog/actions/runs/4838397232/jobs/8622844030

TODO:
- [x] `$(format-json --cast)`
- [x] syslog-ng type-aware comparisons (check all filters)
- [x] `FAILED tests/test_beyondtrust.py::test_beyondtrust_parts - assert 2 == 1` (1 failed, 560 passed))

Depends on:
- syslog-ng/syslog-ng#4415
- syslog-ng/syslog-ng#4394
- syslog-ng/syslog-ng#4401
- syslog-ng/syslog-ng#4390
- syslog-ng/syslog-ng#4410

### CODE REVIEW

**Comment by MrAnno** [comment]
@rjha-splunk SC4S is probably one of the biggest power users of syslog-ng :)
I've found quite a few syslog-ng v4 bugs during the upgrade.

The `ci-main` GitHub action finally passes on the upgraded image.
Do you happen to have any additional tests worth trying on the image `ghcr.io/mranno/syslog-ng-splunk-connector:latest`?
If there is any chance of finding any more bugs, I think it would be important to fix them before releasing syslog-ng v4.2.

**Comment by MrAnno** [comment]
In the meantime, Alpine-based images with the latest version of syslog-ng are available to test for anyone interested:

https://github.com/axoflow/syslog-ng-docker/pkgs/container/syslog-ng-splunk-connector

**Comment by bparmar-splunk** [comment]
> In the meantime, Alpine-based images with the latest version of syslog-ng are available to test for anyone interested:
> 
> https://github.com/axoflow/syslog-ng-docker/pkgs/container/syslog-ng-splunk-connector

Yes @MrAnno,
We will try these changes with Alpine based image (in this sprint) and are also planning to release beta version of SC4S.

**Comment by MrAnno** [comment]
@bparmar-splunk Sounds great, thank you.

**Comment by bparmar-splunk** [comment]
@MrAnno,
We have few queries about this upgrade.
Could you please share your availability so that can connect and discuss along with @rjha-splunk ?

**Comment by rjha-splunk** [comment]
@mateuszpierzchala-splunk please review , test on 3.36 and merge in development

**Comment by MrAnno** [comment]
@mateuszpierzchala-splunk @rjha-splunk
FYI syslog-ng v4.2.0 has been released.

**Pull request closed without merging**
