### PR TITLE
add ipv6 support

### PR DESCRIPTION
**Pull request by michaelw**

### CODE REVIEW

**Comment by michaelw** [comment]
CLA link is 404 for me: https://github.com/splunk/addonfactory-test-releaseci/blob/main/CLA.md
Is there an updated one?

**Review by rfaircloth-splunk — APPROVED** [review]

**Comment by rfaircloth-splunk** [comment]
correct CLA link is https://github.com/splunk/splunk-connect-for-syslog/blob/master/CLA.md

**Comment by michaelw** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by michaelw** [comment]
recheck

**Pull request merged**
