### PR TITLE
Preparation/minor fixes for the syslog-ng v4 upgrade

### PR DESCRIPTION
**Pull request by MrAnno**
I've started testing [splunk-connect-for-syslog](https://github.com/splunk/splunk-connect-for-syslog) with syslog-ng v4.

This PR is the result of my tests, it makes SC4S operable with syslog-ng 4.

There are quite a few warnings that need to be fixed before upgrading to v4, but I'd submit them in a separate pull request.

### CODE REVIEW

**Comment by rjha-splunk** [comment]
@bparmar-splunk Please review it , we can discuss it post 28/04/2023

**Comment by MrAnno** [comment]
@rjha-splunk @bparmar-splunk Could you start the test workflows for me, please?

**Comment by MrAnno** [comment]
FYI I'm investigating one last issue regarding time-zone detection.

**Comment by MrAnno** [comment]
I checked locally, and all SC4S functional tests passed on top of the current master branch of syslog-ng (with a lot of warnings, which I intend to fix later).

One exception was `tests/test_common.py::test_check_config_version`, but that's normal.

**Comment by MrAnno** [comment]
Oh, sorry I didn't notice that.

I'll try to do a full 4.0 upgrade in the upcoming days and update the PR.

Until then, upgrading to v3.37 seems to be an option for you guys as `grouping-by(persist-name())` is available there.

**Comment by MrAnno** [comment]
FYI I've started doing a full v4 upgrade and realized that due to the new message field typing functionality in v4, it has become a bit difficult to implement Python parsers that want to handle everything as strings.

Long story short, I'm going to add new functionality to the Python binding to make this use-case easier to implement on top of a new syslog-ng version, so the v4 upgrade is going to be a 4.2 upgrade.

Since syslog-ng v4.2 can be expected only in May, I'd propose the following:
- Let's do a syslog-ng 3.38 upgrade in SC4S
- Test, review, and merge this PR with a syslog-ng 3.38-based SC4S version
- Open a new PR with the full syslog-ng 4.2 upgrade (I'm working on this; it can be reviewed and tested using the master branch of syslog-ng)
- Wait for a syslog-ng 4.2 release
- Merge the syslog-ng 4.2 upgrade

@rjha-splunk What do you think?

**Comment by MrAnno** [comment]
@rjha-splunk Sorry for the confusion. Upgrading to v3.38 will not work either as the `persist-name()` option is buggy there...
Let's wait for syslog-ng 4.2 then...

**Pull request closed without merging**
