### PR TITLE
feat: Add basic support for parsing syslog messages from Nokia SR Linux devices

### PR DESCRIPTION
**Pull request by jbemmel**
Sample messages from testing:
```
1/26/23
3:28:01.000 PM	
sr_xdp_lc_1: acl|1416|1874|00011|D: Type: Ingress IPv6 Filter: cpm-ipv6-filter Sequence Id: 390 Action: Drop Interface: mgmt0.0 Packet length: 70 IP Source: fe80::42:acff:fe14:1402 Destination: ff02::2 Protocol: 58 Dscp: 0 ICMP6 Type: 133 Code: 0

    host = leaf1
    source = sc4s
    sourcetype = nokia:router

	1/26/23
3:27:56.000 PM	
sr_xdp_lc_1: acl|1416|1874|00010|D: Type: Ingress IPv6 Filter: cpm-ipv6-filter Sequence Id: 390 Action: Drop Interface: mgmt0.0 Packet length: 107 IP Source: fe80::8434:51ff:fecd:c001 Destination: ff02::fb Protocol: 17 Dscp: 0

    host = leaf1
    source = sc4s
    sourcetype = nokia:router

	1/26/23
3:27:55.000 PM	
sr_supportd: debug|1110|1120|00004|I: common    log_configuration.cc:339 LogSetConfigLevelsToWarning  'debug' subsystem log levels raised to Warning

    host = leaf1
    source = sc4s
    sourcetype = nokia:router
```

### CODE REVIEW

**Comment by jbemmel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jbemmel** [comment]
recheck

**Comment by jbemmel** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by jbemmel** [comment]
recheck

**Comment by bparmar-splunk** [comment]
@jbemmel,
It seems there is some issue with the parser. Could you please check?
And also, the logs which you have mentioned (in comment above) is not as per RFC complaint. Could you please share the raw logs over DM to validate?

**Comment by jbemmel** [comment]
The output above is after Splunk processing, it marks the input as RFC compliant. Can share more details in about 2 weeks

**Comment by jbemmel** [comment]
@bparmar-splunk when I replace "vendor_product" with separate vendor() and product() lines, it passes the test but it breaks my Splunk 9.0.3 test setup :(

For some reason it only works when I use vendor_product - please advice

**Comment by bparmar-splunk** [comment]
@jbemmel,
Please make use of SC4S image from github. [[Docs](https://splunk.github.io/splunk-connect-for-syslog/main/upgrade/)]

**Pull request closed without merging**
