### PR TITLE
feat(f5): Support APM source type

### LINKED ISSUE #1423: F5 Parser Missing Sourcetype
F5 TA includes a sourcetype `f5:bigip:apm:syslog` that is not included in SC4S.  This is auto sourcetyped from `f5:bigip:syslog` within the TA so SC4S should add a write to the block parser.

```
            rewrite{
                r_set_splunk_dest_update(
                    sourcetype('f5:bigip:apm:syslog')
                    condition(message(':\s(?:\d{4})[0-9A-Fa-f]{4}:\d+:\s+(?:[^:\s]{1,100}:[^:\s]{1,100}:\s*)?[0-9a-f]{8}:'))
                );
            };
```

### PR DESCRIPTION
**Pull request by satellite-no**
Added rewrite section to f5 to account for sourcetype `f5:bigip:apm:syslog`. 

Fixes #1423

### CODE REVIEW

**Review by rfaircloth-splunk — CHANGES_REQUESTED** [review]
For this regex we need a test to verify can you add a test, I can help with that step if you can add an event raw as a comment

**Comment by satellite-no** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by satellite-no** [comment]
Sounds good! Below is an example message that can be used.  My regex was a rip off of the TA 2680. 

```
<141>Feb  3 13:24:14 F5-V1-EX.HDKS.edu notice tmm1[12390]: 01490500:5: /Common/My_HDKS-Hybrid:Common:e03c2ca8: New session from client IP 71.31.126.0 (ST=Arizona/CC=US/C=NA) at VIP 192.164.20.28 Listener /Common/HDKS-ADFS.app/HDKS-ADFS_adfs_vs_443 (Reputation=Unknown)
hostname="F5-V1-EX.HDKS.edu",errdefs_msgno="01490521:5:",partition_name="Common",session_id="9e48a3a4",Access_Profile="/Common/My_HDKS-Hybrid",Partition="Common",Session_ID="9e48a3a4",Bytes_In="11858",Bytes_Out="1955"
```

**Comment by rfaircloth-splunk** [comment]
I added a new test and adjusted your regex, the ta regex assumed it was matching program but in sc4s program and message are in seperate fields

**Comment by satellite-no** [comment]
Oh, fantastic!!  Thank you!

**Pull request merged**
